apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment

secretGenerator:
  - name: vellum-env
    namespace: kubeflow-vellum
    envs:
      - .env

# generatorOptions:
#   disableNameHash: true
