apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-api-server
        env:
        - name: OBJECTSTORECONFIG_HOST
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: minioServiceHost
        - name: OBJECTSTORECONFIG_PORT
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: minioServicePort
