apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow-vellum
  labels:
    app.kubernetes.io/part-of: kubeflow-profile
    istio-injection: enabled
    katib.kubeflow.org/metrics-collector-injection: enabled
    pipelines.kubeflow.org/enabled: "true"
    serving.kubeflow.org/inferenceservice: enabled
    pod-security.kubernetes.io/enforce: baseline
  annotations:
    owner: vellum@example.com
