#!/usr/bin/env bash
# Consolidated Port-Forward Script
# Usage: ./scripts/connect.sh

set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/cluster-common.sh"

ensure_project_root
load_env_file
require_commands kubectl
require_kubectl_access

RUNTIME_ENV_FILE="$PROJECT_ROOT/.vellum-runtime.env"
declare -a RESERVED_LOCAL_PORTS=()
LAST_PORT_FORWARD_PORT=""

echo "🔌 Establishing port-forwards for the completed Kind Phase 1 stack..."

pkill -f "kubectl port-forward" >/dev/null 2>&1 || true
sleep 2

HYBRID=false
if [[ "${1:-}" == "--hybrid" ]]; then
  HYBRID=true
  echo "🚀 Hybrid Mode: Skipping Backend (8006) and Frontend (9090) port-forwards..."
fi

initialize_runtime_env() {
  cat > "$RUNTIME_ENV_FILE" <<EOF
# Auto-generated by scripts/connect.sh
HYBRID_MODE=${HYBRID}
EOF
}

write_runtime_env() {
  local key="$1"
  local value="$2"

  printf '%s=%s\n' "$key" "$value" >> "$RUNTIME_ENV_FILE"
}

port_reserved_in_run() {
  local candidate_port="$1"
  local reserved_port

  for reserved_port in "${RESERVED_LOCAL_PORTS[@]}"; do
    if [[ "$reserved_port" == "$candidate_port" ]]; then
      return 0
    fi
  done

  return 1
}

select_local_port() {
  local preferred_port="$1"
  local attempts="${2:-50}"
  local candidate_port="$preferred_port"
  local count=0

  while [[ "$count" -lt "$attempts" ]]; do
    if ! port_reserved_in_run "$candidate_port" && port_is_available "$candidate_port"; then
      echo "$candidate_port"
      return 0
    fi

    candidate_port=$((candidate_port + 1))
    count=$((count + 1))
  done

  echo "No free localhost port found after ${attempts} attempts starting at ${preferred_port}." >&2
  return 1
}

start_port_forward() {
  local namespace="$1"
  local resource="$2"
  local remote_port="$3"
  local preferred_local_port="$4"
  local label="$5"
  local port_env_key="$6"
  local url_env_key="$7"
  local url_suffix="${8:-}"
  local local_port
  local url

  if ! kubectl get -n "$namespace" "$resource" >/dev/null 2>&1; then
    echo "⚠️  Skipping ${label}: ${resource} not found in namespace ${namespace}."
    return 0
  fi

  local_port="$(select_local_port "$preferred_local_port")"
  RESERVED_LOCAL_PORTS+=("$local_port")
  nohup kubectl port-forward -n "$namespace" "$resource" "${local_port}:${remote_port}" > /dev/null 2>&1 &
  LAST_PORT_FORWARD_PORT="$local_port"
  url="http://localhost:${local_port}${url_suffix}"

  if [[ "$local_port" != "$preferred_local_port" ]]; then
    echo "ℹ️  ${label}: preferred localhost port ${preferred_local_port} is busy, using ${local_port}."
  fi

  write_runtime_env "$port_env_key" "$local_port"
  write_runtime_env "$url_env_key" "$url"
  echo "✅ ${label}: ${url}"
}

initialize_runtime_env

start_port_forward istio-system svc/istio-ingressgateway 80 8086 "Dashboard" VELLUM_DASHBOARD_PORT VELLUM_DASHBOARD_URL
start_port_forward qdrant svc/qdrant 6333 6333 "Qdrant" VELLUM_QDRANT_PORT VELLUM_QDRANT_URL
start_port_forward kubeflow svc/ml-pipeline 8888 8888 "KFP API (optional direct-debug path)" VELLUM_KFP_PORT VELLUM_KFP_URL
start_port_forward kubeflow-vellum svc/embeddings-service 80 8082 "Embeddings" VELLUM_EMBEDDINGS_PORT VELLUM_EMBEDDINGS_URL /v1
start_port_forward kubeflow svc/minio-service 9000 9000 "MinIO" VELLUM_MINIO_PORT VELLUM_MINIO_URL
write_runtime_env VELLUM_MINIO_ENDPOINT "localhost:${LAST_PORT_FORWARD_PORT}"

if [[ "$HYBRID" == false ]]; then
  start_port_forward kubeflow-vellum svc/backend 8000 8006 "Backend" VELLUM_BACKEND_PORT VELLUM_BACKEND_URL /docs
fi

if bool_is_true "$ENABLE_LOCAL_LLM"; then
  if kubectl get deployment llm-service-predictor -n kubeflow-vellum -o jsonpath='{.spec.replicas}' 2>/dev/null | grep -qx '1'; then
    start_port_forward kubeflow-vellum svc/llm-service-predictor 80 8081 "LLM Service" VELLUM_LLM_PORT VELLUM_LLM_URL /v1
  else
    echo "ℹ️  Local LLM deployment is scaled down; skipping LLM port-forward."
  fi
else
  echo "ℹ️  ENABLE_LOCAL_LLM=${ENABLE_LOCAL_LLM}; skipping LLM port-forward."
fi

if [[ "$HYBRID" == false ]]; then
  start_port_forward kubeflow-vellum svc/frontend 80 9090 "Frontend" VELLUM_FRONTEND_PORT VELLUM_FRONTEND_URL
fi

write_runtime_env VELLUM_RUNTIME_ENV_FILE "$RUNTIME_ENV_FILE"
write_runtime_env VELLUM_QDRANT_HOST localhost

echo "Running in background. Kill with 'pkill -f \"kubectl port-forward\"'."
echo "Runtime port bindings saved to ${RUNTIME_ENV_FILE}."
