apiVersion: v1
kind: Service
metadata:
  name: chroma-service
  namespace: kubeflow
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app.kubernetes.io/name: chromadb
